### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by DanielusG** [kaistAI/SelFee#2]
I didn't know how else to communicate my thoughts about the project, so I opened this issue.

The project is absolutely interesting and shows its fruits! but there is something particular I noticed, while testing it using your demo, I noticed that even if the model gave bad answers or was hallucinating, the feedback it gave itself was always very positive and the ratings are never lower than 8.

I checked the training dataset on the huggingface page, and noticed that there is also a large presence of positive feedback in the dataset!

So I thought, what if a lot of bad examples were also introduced into the dataset with the corresponding feedback misjudging the answer? Then the model should become more aware of what is right or wrong in the answers.

What do you think?

I really appreciate your work, a huge thank you!

**Comment by seonghyeonye** [comment]
Thank you for your suggestion! We also agree with the limitations of the current model and definitely think that intentionally incorporating low-rating training examples is an interesting direction. 
We have actually done a preliminary experiment on LLaMA-7B fine-tuning by collecting relatively low-quality responses from an open-sourced model, but it did not lead to significant improvements. 
However, we think that there is more to explore in this direction by experimenting with different settings, such as varying the model scale and employing diverse methods to augment the training data.
