### ISSUE TITLE
uncensored version?

### ISSUE THREAD

**Issue by EduardTalianu** [kaistAI/SelFee#5]
Hi,
Realy nice project. Any plan on releasing an uncensored version? Usually they have better performance.
Also a wiki with use-cases and how-to would be nice.
Also, an increase of the context window seems possible, see the latest projects released by theBloke on huggingface/ kaiokendev work.

Kudos,

**Comment by seonghyeonye** [comment]
Hi, sorry for the late response. 
Could you specify what you mean by uncensored version?
We also agree that the increase of the context window using other techniques would lead to better performance since our work leads to increased sequence length.
Thank you.

**Comment by EduardTalianu** [comment]
Hi, thanks for the reply. 

Looking forward for your next model :)
An uncensored model is practicaly a model for which responses such as "as an AI language model..." are removed. So for instance  responses that contained alignment / moralizing are removed and the model is actually responding and not censoring some responses. See for instance uncensored models on hugginface such as: https://huggingface.co/ehartford/Wizard-Vicuna-13B-Uncensored or datasets such as https://huggingface.co/datasets?sort=trending&search=uncensored

Related to the context size a recent model seem to have a 32K context window: https://huggingface.co/togethercomputer/Llama-2-7B-32K-Instruct

**Comment by seonghyeonye** [comment]
Thank you for your suggestion! We will definitely try to explore those directions :)
