### ISSUE TITLE
 Encountered error while generating package metadata

### ISSUE THREAD

**Issue by georgebecerescu** [kaistAI/SelFee#6]
Collecting torch==2.0.1 (from -r requirements.txt (line 4))
  Downloading torch-2.0.1-cp311-cp311-manylinux1_x86_64.whl (619.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 619.9/619.9 MB 3.0 MB/s eta 0:00:00
Collecting flash-attn==0.2.8 (from -r requirements.txt (line 5))
  Using cached flash_attn-0.2.8.tar.gz (1.8 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-tjhjvhnh/flash-attn_d4c66fc1204a49cf9a44de9ebbba6e8d/setup.py", line 10, in <module>
          import torch
      ModuleNotFoundError: No module named 'torch'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details

**Comment by seonghyeonye** [comment]
Hi, sorry for the late response.
There seems to be an issue with the torch installation.
Could you follow the installation guideline specified in https://pytorch.org/  (based on your environment setting)?
Thank you.
